openapi: 3.0.0
info:
  title: Accounts API Documentation
  description: Endpoints related to Accounts management
  version: 1.0.0

tags:
  - name: Accounts
    description: Endpoints related to Accounts management

paths:
  /api/accounts/createAccount:
    post:
      tags:
        - Accounts
      summary: Create a new account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Successfully created account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
        '409':
          description: Incorrect password
        '500':
          description: Internal server error
        '501':
          description: Unexpected server error

  /api/accounts/changeAccountName/{id}:
    patch:
      tags:
        - Accounts
      summary: Change the name of an Account
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the Account to change the name for
        - in: query
          name: newAccountName
          required: true
          schema:
            type: string
          description: The new name for the Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeAccountNameRequest'
      responses:
        '201':
          description: Account name updated successfully
        '404':
          description: User not found / Account is not found
        '409':
          description: Incorrect password
        '500':
          description: Internal server error
        '501':
          description: Unexpected server error

  /api/accounts/deleteAccount/{id}:
    delete:
      tags:
        - Accounts
      summary: Delete an account
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the account to delete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAccountRequest'
      responses:
        '201':
          description: Account deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAccountResponse'
        '404':
          description: Unauthorized request
        '401':
          description: Internal server error
        '501':
          description: Unexpected server error

  /api/accounts/transactions/transfer/account-to-account:
    post:
      tags:
        - Accounts
      summary: Transfer money to another account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferToAccountRequest'
      responses:
        '200':
          description: Transaction completed successfully
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/TransferToAccountResponse'
        '400':
          description: Not enough balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: The same account number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found / Account is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

/api/accounts/transactions/transfer/account-to-card:
    post:
      tags:
        - Accounts
      summary: Transfer money to  card
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferToAccountRequest'
      responses:
        '200':
          description: Transaction completed successfully
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/TransferToAccountResponse'
        '400':
          description: Not enough balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: The same account number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found / Account is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

/api/accounts/transactions/transfer/viaPhoneNumber:
    post:
      tags:
        - Accounts
      summary: Transfer money via phone number
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferToAccountRequestViaPhone'
      responses:
        '200':
          description: Transaction completed successfully
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/TransferToAccountResponse'
        '400':
          description: Not enough balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: The same account number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found / Account is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

/api/accounts:
    get:
      tags:
        - Accounts
      summary: Get accounts
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: count
          schema:
            default: Infinity
          description: Number of accounts to retrieve
      responses:
        '200':
          description: Successfully retrieved accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateAccountRequest:
      type: object
      properties:
        currency:
          type: string
          example: USD
        accountType:
          type: string
          example: Current

    CreateAccountResponse:
      type: object
      properties:
        account:
          type: object
          properties:
            _id:
              type: string
              example: 667c2377bae36c47d9806b25
            userId:
              type: string
              example: 667c2377bae36c47d9806b25
            accountNumber:
              type: string
              example: 7648951913473405
            balance:
              type: number
              format: float
              example: 0
            currency:
              type: string
              example: USD
            accountType:
              type: string
              example: Current

    ChangeAccountNameRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          example: '1234'
      description: The Password to authorize the change

    DeleteAccountRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          example: 'user password'
      description: The Password to authorize the deletion

    DeleteAccountResponse:
      type: object
      properties:
        message:
          type: string
          example: Account deleted successfully

    TransferToAccountRequest:
      type: object
      required:
        - creditNumber
        - debitNumber
        - password
        - amount
      properties:
        creditNumber:
          type: string
          example: '123456789012345'
        debitNumber:
          type: string
          example: '6566971968343332'
        password:
          type: string
          example: 'Arman111'
        amount:
          type: number
          format: float
          example: 100.0
        notes:
          type: string
          example: 'Some notes'
          
    TransferToAccountRequestViaPhone:
      type: object
      required:
        - creditNumber
        - debitNumber
        - password
        - amount
      properties:
        creditNumber:
          type: string
          example: '123456789012345'
        debitNumber:
          type: string
          example: '099999999'
        password:
          type: string
          example: 'Arman111'
        amount:
          type: number
          format: float
          example: 100.0
        notes:
          type: string
          example: 'Some notes'

    TransferToAccountResponse:
      type: object
      properties:
        message:
          type: string
          example: Transaction completed successfully

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Error message  

    Account:
      type: object
      properties:
        _id:
          type: string
          example: '60d0fe4f5311236168a109ca'
        userId:
          type: string
          example: "60d0fe4f5311236168a109ca"
        cardId:
          type: string
          example: '60d0fe4f5311236168a109ca'
        accountNumber:
          type: string
          example: '1111111111111111'
        balance:
          type: number
          example: 0
        currency:
          type: string
          example: 'AMD'
        accountType:
          type: string
          example: 'Saving'
        accountName:
          type: string
          example: 'My current account'
        hasCard:
          type: boolean
          example: 'true'

