openapi: 3.0.0
info:
  title: Cards API Documentation
  description: Endpoints related to user card management
  version: 1.0.0

tags:
  - name: Cards
    description: Endpoints related to user card management

paths:
  /api/cards/createCard:
    post:
      tags:
        - Cards
      summary: Create a new card
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCardRequest'
      responses:
        '201':
          description: Successfully created card
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCardResponse'
        '401':
          description: Unauthorized request
        '404':
          description: Account or User not found
        '409':
          description: Account already attached to another card
        '500':
          description: Internal server error

  /api/cards/changeCardName/{id}:
    patch:
      tags:
        - Cards
      summary: Change the name of a card
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the card to change the name for
        - in: query
          name: newCardName
          required: true
          schema:
            type: string
          description: The new name for the card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeCardNameRequest'
      responses:
        '201':
          description: Card name updated successfully
        '404':
          description: User not found / Card is not found
        '409':
          description: Incorrect pin
        '500':
          description: Internal server error
        '501':
          description: Unexpected server error

  /api/cards/changePin/{id}:
    patch:
      tags:
        - Cards
      summary: Change pin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the card to change the pin 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeCardPinRequest'
      responses:
        '201':
          description: Card pin updated successfully
        '404':
          description: User not found / Card is not found
        '409':
          description: Incorrect pin
        '500':
          description: Internal server error
        '501':
          description: Unexpected server error

  /api/cards/deleteCard/{id}:
    delete:
      tags:
        - Cards
      summary: Delete a card
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the card to delete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteCardRequest'
      responses:
        '201':
          description: Card deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCardResponse'
        '401':
          description: Unauthorized request
        '500':
          description: Internal server error
        '501':
          description: Unexpected server error

  /api/cards/transactions/transfer/card-to-account:
    post:
      tags:
        - Cards
      summary: Transfer money to  account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferToAccountRequest'
      responses:
        '200':
          description: Transaction completed successfully
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/TransferToAccountResponse'
        '400':
          description: Not enough balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: The same account number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found / Account is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/cards/transactions/transfer/card-to-card:
    post:
      tags:
        - Cards
      summary: Transfer money to  card
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferToAccountRequest'
      responses:
        '200':
          description: Transaction completed successfully
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/TransferToAccountResponse'
        '400':
          description: Not enough balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: The same account number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found / Account is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/cards/transactions/transfer/viaPhoneNumber:
    post:
      tags:
        - Cards
      summary: Transfer money via phone number
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferToAccountRequestViaPhone'
      responses:
        '200':
          description: Transaction completed successfully
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/TransferToAccountResponse'
        '400':
          description: Not enough balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: The same account number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found / Account is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/cards:
    get:
      tags:
        - Cards
      summary: Get cards
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: count
          schema:
            default: Infinity
          description: Number of cards to retrieve
      responses:
        '200':
          description: Successfully retrieved cards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/card'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateCardRequest:
      type: object
      properties:
        cardType:
          type: string
        cardName:
          type: string
        accountId:
          type: string
  

    CreateCardResponse:
      type: object
      properties:
        message:
          type: string
          example: Card created successfully
        card:
          type: object
          properties:
            userId:
              type: string
              example: 667c2377bae36c47d9806b25
            cardNumber:
              type: string
              example: 7648951913473405
            cardHolderName:
              type: string
              example: Arman Mikoyan
            expirationDate:
              type: string
              example: Sat Jun 26 2027 18:50:43 GMT+0400 (Armenia Standard Time)
            cvv:
              type: string
              example: $2b$10$wlgxRtU9NX9Dnuan.mW0COXFtgq12KQcRYV1E1BRuueRRtLEfP2Je
            pin:
              type: string
              example: $2b$10$ybo0DRX4UEnIRa1FPEgXluoR0eJmWur/qPbV6KLU8wxIHEFY7KoVO
            cardType:
              type: string
              example: Visa
            cardName:
              type: string
              example: string
            balance:
              type: number
              example: 0
            currency:
              type: string
              example: AMD
            _id:
              type: string
              example: 667c2ac3b951057ce625e982
            __v:
              type: number
              example: 0

    ChangeCardNameRequest:
      type: object
      required:
        - pin
      properties:
        pin:
          type: string
          example: '1234'
      description: The PIN to authorize the change

    ChangeCardPinRequest:
      type: object
      required:
        - oldPin
        - newPin
      properties:
        oldPin:
          type: string
          example: '1234'
        newPin:
          type: string
          example: '1234'
      description: The new Pin

    TransferToAccountRequestViaPhone:
      type: object
      required:
        - creditNumber
        - debitNumber
        - password
        - amount
      properties:
        creditNumber:
          type: string
          example: '123456789012345'
        debitNumber:
          type: string
          example: '099999999'
        password:
          type: string
          example: 'Arman111'
        amount:
          type: number
          format: float
          example: 100.0
        notes:
          type: string
          example: 'Some notes'

    DeleteCardRequest:
      type: object
      required:
        - pin 
      properties:
        pin:
          type: string
          example: '1234'
      description: The PIN to authorize the deletion

    DeleteCardResponse:
      type: object
      properties:
        message:
          type: string
          example: Card deleted successfully
  
    TransferToAccountRequest:
      type: object
      required:
        - creditNumber
        - debitNumber
        - password
        - amount
      properties:
        creditNumber:
          type: string
          example: '123456789012345'
        debitNumber:
          type: string
          example: '6566971968343332'
        password:
          type: string
          example: 'Arman111'
        amount:
          type: number
          format: float
          example: 100.0
        notes:
          type: string
          example: 'Some notes'

    TransferToAccountResponse:
      type: object
      properties:
        message:
          type: string
          example: Transaction completed successfully
    
    card:
      type: object
      properties:
        _id:
          type: string
          example: '60d0fe4f5311236168a109ca'
        userId:
          type: string
          example: "60d0fe4f5311236168a109ca"
        accountId:
          type: string
          example: '60d0fe4f5311236168a109ca'
        cardNumber:
          type: string
          example: '1111111111111111'
        balance:
          type: number
          example: 0
        currency:
          type: string
          example: 'AMD'
        cardType:
          type: string
          example: 'Saving'
        cardsName:
          type: string
          example: 'My current card'
        hasCard:
          type: boolean
          example: 'true'
        pin:
          type: number
          example: 'hashed'
        cvv:
          type: number
          example: 'hashed'
        expirationDate:
          type: date
          example: '09 12 2090'

